### ISSUE TITLE
Nahrazení `process.cwd()` za relativní cesty u `require`

### ISSUE THREAD

**Issue by langpavel** [JakubMrozek/Zdrojak#7]
process.cwd() je závislé na pracovním adresáři.

Pokud by byl skript spouštěn z jiného umístění, není zaručeno, že cesty na které se `require` odkazuje budou platné.

**Comment by JakubMrozek** [comment]
Díky za komentář. Řešili jsme to po mailu. Je to věc názoru, mně přijde přehlednější používat:

``` javascript
var lib = require(process.cwd() + '/abc');
```

než používat 

``` javascript
var lib = require('../../../abc');
```

Nicméně do některého z článku tohle zmíním a nechám na čtenáři, aby si vybral, kterou variantu bude preferovat.

**Comment by langpavel** [comment]
tohle je velice špatný přístup, který nebude fungovat u žádného modulu instalovaného do `node_modules` přez `npm`, takže to není věc názoru, ale bug :-)

Nemyslím si, že je dobré mást čtenáře, protože tohle se prostě bude muset odnaučit používat, pokud jednou začne psát vlastní moduly…

**Comment by JakubMrozek** [comment]
Bug to není, funguje to všem. Pro tenhle use case to ale problém není. Jako jeden z posledních, ne-li úplně poslední díl, plánuji vydávání vlastních balíčků a tam to zmíním. Pokud si člověk buduje aplikaci ala tenhle shop, tak to může v klidu používat dál.
